[package]
name = "hopter_conf_params"
edition = "2021"
# Put a huge compatible semantic version number here so that the local
# configuration parameter definition can override the default value having
# a smaller semantic version number.
version = "0.3.1000"
license = "MIT"
description = "Hopter embedded operating system configuration parameters."
repository = "https://github.com/hopter-project/hopter-conf-params"
readme = false

[dependencies]
